global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hotel-reservas-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: "hotel-reservas"